# Generated by Django 5.0.6 on 2024-06-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
