# Generated by Django 5.1a1 on 2024-06-18 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommandApi', '0001_initial'),
        ('productAPI', '0002_alter_productlist_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productAPI.productlist'),
        ),
        migrations.AlterField(
            model_name='command',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
